{{ range $appName, $appConfig := .Values.apps }}
{{- if $appConfig.pdb }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ $appConfig.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ $appName }}
{{- end }}
{{- end }}
