{{ range $appName, $appConfig := .Values.apps }}
{{- $appValues := dict
      "component"           $appName
      "Values"              $.Values
      "Release"             $.Release
      "labels" (default (dict) $.Values.labels)
    -}}
{{- if $appConfig.pdb }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "standard-app.labels" $appValues | nindent 2 }}
spec:
  minAvailable: {{ $appConfig.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ $appName }}
{{- end }}
{{- end }}
