image: us-central1-docker.pkg.dev/cloudkite-infra-ops/cloudkite-docker-images/example-image
tag: example_tag
pvcs: # A list Persistent Volume Claims that can be mounted to the pods
  - name: pvc1
    storage: 2Gi
    storageClassName: my-storage-class # Optional (If not provided it defaults to the default storage class)
    accessModes:
      - ReadWriteOnce
  ## Use if deploying on the GKE spot nodes (e.g. for NAP)
  # nodeType: spot
labels:
  label1: somevalue
  label2: anothervalue

ingress:  # NOTE: >0.8.0 DEPRECATES this, USE .Values.ingresses
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/api)(.*) $2 break;
  # hostPaths:
  #   - host: "my.domain.name.com"
  #     servicePort: 3000
  #     serviceName: cloudkite-app-1
  #     path: "/"
  #   - host: "my-other.domain.name.com"
  #     servicePort: 3000
  #     serviceName: cloudkite-app-1
  #     path: "/someprefix"
  # tls:
  #   - secretName: my-domain-name-com-tls
  #     hosts:
  #       - "my.domain.name.com"
  #       - "my-other.domain.name.com"
  hosts:
    - test.dev.someorg.com
    - other.domain.name.com
  # option to add a pre-generated certficate secret
  # secretName: dev-wildcard-certificate
  paths:
    - path: /
      pathType: Prefix
      servicePort: 5000
      serviceName: cloudkite-app-1
    - path: /api
      pathType: Prefix
      servicePort: 3003
      serviceName: cloudkite-app-2

ingresses:
  cloudkite-app-1-webhook:
    # ingressClass: set this to override the ingress class used for the ingress (if not set, 
    # the ingress will use the ingress class set as defualt in the cluster)
    ingressClass: nginx-external
    annotations:
      kubernetes.io/tls-acme: "true"
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - test-callbacks.dev.someorg.com
    # option to add a pre-generated certficate secret
    # secretName: dev-wildcard-certificate
    paths:
      - path: /webhook
        pathType: Prefix
        servicePort: 5000
        serviceName: cloudkite-app-1
  # additional ingresses are optional
  cloudkite-app-2-webhook:
    annotations:
      kubernetes.io/tls-acme: "true"
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - test-callbacks.dev.someotherorg.com
  # option to add a pre-generated certficate secret
  # secretName: dev-wildcard-certificate
    paths:
      - path: /webhook
        pathType: Prefix
        servicePort: 5000
        serviceName: cloudkite-app-2

env:
  GLOBAL_ENV1: value1
  GLOBAL_ENV2: value2

serviceAccounts:
  app-1:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ASSUME_ROLE_NAME
  app-2:
    annotations:
      iam.gke.io/gcp-service-account: GOOGLE_SERVICE_ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com


gateways:
  example-gateway:
    enabled: true
    annotations:
      networking.gke.io/certmap: example-gateway-map # Optional, used for Google managed certificate, managed certificate and map can be created manually https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways#create_a_certificate_map
    gatewayClass: gke-l7-global-external-managed # Default to GKE L7 Global External Managed Gateway you can change this to internal gateway class
    listeners:
      - name: https
        protocol: HTTPS
        port: 443
        # Optional, if not specified it defaults to allowing routes in the same namespace. For more permissive settings, you can specify the namespaces or labels: https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways#create_a_certificate_map.
        allowedRoutes: 
          namespaces:
            from: Same # Allow routes in the same namespace by default
    # Optional, if you want to specify a specific external reserved or internal address for the Gateway, if left empty, the gateway will use the default address for the cluster based on the gateway class.
    addresses:
      - type: NamedAddress
        value: example-ip-address-name # Name of external IP address
    # Optional, if you want to specify labels for the allowed routes, this is useful for more fine-grained control over which routes are allowed to be used with this gateway. in this case the routes specified in the rules.
    # allowedRoutesLabels:
      # app: example-app
      # environment: production
    hostnames:
      - api.dev.example.com
      - api.example.com
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /v1
        backendRefs:
        - name: example-app-2
          port: 3003
      - matches:
        - path:
            type: PathPrefix
            value: /v2
        backendRefs:
        - name: example-app-2-web-headless
          port: 3003


apps:
  # you can specify init containers and containers for each deployment for a fine tuning (example-app-1), or use a simplified version in case you only need one container (example-app-2)
  # you can specify parameters on multiple levels: 
  #     * global (env, secrets)
  #     * app/deployment and container/initcontainer (env, secrets, service, redinessProbe, resources)
  example-app-1:
    strategyType: RollingUpdate # Recreate or RollingUpdate
    initContainers:
      exampleinitcontainer-1:
        image: google/cloud-sdk
        command: ["/bin/sh", "-c"]
        args:
          - /etc/scripts/script1.sh
        secrets:
          - secretKey: example
    containers:
      example-container-1:
        image: us-central1-docker.pkg.dev/cloudkite-infra-ops/cloudkite-docker-images/app-1
        tag: tag-1
        imagePullPolicy: None
        # mpa:
        #   mode: noset
        #   maxReplicas: 12
        #   minReplicas: 3
        #   cpuTarget: 75
        ports:
          - name: api-rest
            containerPort: 5000
            protocol: TCP
          - name: api-grpc
            containerPort: 5010
            protocol: TCP
          - name: api-metrics
            containerPort: 5005
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
        env:
          CONTAINER_ENV1: asd
          CONTAINER_ENV2: qwe
      example-container-2:
        image: us-central1-docker.pkg.dev/cloudkite-infra-ops/cloudkite-docker-images/app-1
        tag: tag-1
        imagePullPolicy: None
        ports:
          - name: web
            containerPort: 9000
            protocol: TCP
          - name: web-metrics
            containerPort: 9005
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
        env:
          CONTAINER_ENV1: tyu
          CONTAINER_ENV2: ghu
    services:
      - name: api
        type: ClusterIP
        ports:
          - name: api-rest
            port: 5000
            targetPort: 5000
            protocol: TCP
          - name: api-grpc
            port: 5010
            targetPort: api-grpc
            protocol: TCP
          - name: metrics
            port: 5005
            targetPort: 5005
            protocol: TCP
      - name: web
        type: ClusterIP
        ports:
          - name: web
            port: 9000
            targetPort: 9000
            protocol: TCP
          - name: metrics
            port: 9005
            targetPort: web-metrics
            protocol: TCP
      - name: web-headless
        type: None
        ports:
          - name: web
            port: 9000
            targetPort: web
            protocol: TCP
    serviceAnnotations:
      cloud.google.com/neg: '{"ingress": true}'
    hpa:
      maxReplicas: 3
      minReplicas: 2
      cpuTarget: 50
      # memoryTarget: 95
    replicas: 2
    env:
      APP_ENV1: foo
      APP_ENV2: bar
    secrets:
      - secretKey: appsettings.json
        property: APPSETTINGS_JSON
      - secretKey: SOURCE_PROJECT_ID
    serviceMonitor:
      path: /metrics # default /metrics
      interval: 60s # default 30s
      port: portname
      scrapeTimeout: 10s # default 30s
    podAnnotations:
      custom.annotation/example: "value"
      prometheus.io/scrape: "true"
    # Pod-level security context - at app level
    podSecurityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 3000
  
  example-app-1a:
    # Single structure for containers
    containers:
      container1:
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
      container2:
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
    nodeSelector:
      node-label: "my-node-pool" # Optional, if not specified it defaults to the default node selector for the cluster
    tolerations:
      - key: purpose
        operator: Equal
        value: run-example-app-1a-node
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist


  example-app-2:
    serviceAccount: cloudkite
    vpa:
      mode: Auto
      ## You can specify resources gap for VPA
      # resources:
      #   minAllowed:
      #     memory: 2Gi
      #   maxAllowed:
      #     memory: 4Gi
    # rollout: true
    ports:
      - name: web
        containerPort: 3003
        protocol: TCP
      - name: metrics
        containerPort: 3006
        protocol: TCP
    services:
      - fullname: example-app-2
        type: ClusterIP
        ports:
          - name: web
            port: 3003
            targetPort: 3003
            protocol: TCP
          - name: metrics
            port: 3006
            targetPort: 3006
            protocol: TCP
      - name: web-headless
        type: None
        ports:
          - name: web
            port: 3003
            targetPort: 3003
            protocol: TCP
    serviceAnnotations: {}
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 150m
        memory: 1Gi
    env:
      ENV1: default
    secrets:
      - MONGO_URL
      - REDISCLOUD_URL
      - DATABASE_URL
    podSecurityContext:
      fsGroup: 2000
      runAsNonRoot: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    # GCP settings for the Gateway IAP backend policy
    gatewayBackendPolicy:
      - serviceName: example-app-2 # Name of the service to which the backend policy applies
        clientSecretName: example-app-2 # Name of the Kubernetes secret containing the OAuth2 client secret. SecretKey must be 'key' 
        clientID: 00000-xxxaaazzz.apps.googleusercontent.com

  example-app-3:
    serviceAccount: cloudkite
    vpa:
      mode: Auto
    volumes: 
      - name: static
        mountPath: /static
        type:
          emptyDir: {}
      - name: my-configmap-volume
        mountPath: /etc/scripts
        type:
          configMap:
            name: static-gen-script
            defaultMode: 0777
        configMapData:
          test_script.sh: |
            #!/bin/bash
            DATE=$(date +%d_%m)
  
  example-app-4:
    serviceAccount: cloudkite
    hpa:
      maxReplicas: 3
      minReplicas: 2
      cpuTarget: 80
    replicas: 2
    pdb:
      minAvailable: 2
    vpa:
      mode: Auto
    volumes: 
      - name: static
        type:
          emptyDir: {}
      - name: scripts
        type:
          configMap:
            name: static-gen-script
            defaultMode: 0777
        configMapData:
          test_script.sh: |
            #!/bin/bash
            DATE=$(date +%d_%m)
    initContainers:
      gen-static:
        command:
          - "/usr/local/bin/scripts/test_script.sh"
        volumes:
          - name: scripts
            mountPath: /usr/local/bin/scripts
          - name: static
            mountPath: /var/static
    containers:
      my-app:
        volumes:
          - name: static
            mountPath: /etc/html/static

externalSecret:
  ## Hashicorp Vault
  # secretStoreName: example-name
  # type: vault
  # refreshInterval: 15s
  # secretPath: example-path

  ## AWS secrets manager
  secretStoreName: example-name
  type: aws
  refreshInterval: 1m
  # secretPath: example-path

  # Google Secret Manager
  # secretStoreName: example-name
  # type: gcp
  # refreshInterval: 15s

  # Azure Key Vault
  # secretStoreName: example-name
  # type: azure
  # refreshInterval: 15s

secrets:
  # Vault/GCP/AWS Example
  - secretKey: AWS_ACCESS_KEY_ID   # - secretKey: & property: atribute for secrets are applicable to version 0.2.0, version 0.1.0 uses the key id without artribut names e.g (- AWS_ACCESS_KEY_ID)
  - secretKey: AWS_SECRET_ACCESS_KEY
  # Azure Example
  # Serilog__WriteTo__0__Args__connectionString: SERILOG_CONNECTION_STRING
  # TokenConfig__Secret: TOKEN_CONFIG_SECRET
  # dataFrom:
    # - secret-1
    # - secret/two

jobs:
  jobexample-1:
    annotations:
      annotation1: value1
    command:
      - "cmd1"
    args:
      - "arg1"
    restartPolicy: OnFailure
    resources:
      requests:
        memory: 0.5Gi
        cpu: 50m
      limits:
        memory: 0.5Gi
    volumes:
      - name: secrets
        mountPath: /app/.env
        subPath: .env
        type:
          secret:
            secretName: example-secret
            items:
              - key: env
                path: .env
    nodeSelector:
      node-label: "my-node-pool" # Optional, if not specified it defaults to the default node selector for the cluster
    tolerations:
      - key: purpose
        operator: Equal
        value: run-example-app-1a-node
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist

cronjobs:
  cronjobexample-1:
    schedule: 0 6 * * *
    resources:
      requests:
        memory: 0.5Gi
      limits:
        memory: 0.5Gi
    # image: 
      # repository: dasdqw
    containers:
      cronjobexample-1:
        args: ["node", "bin/updatereviewsfromproducts.js"]
        # image:
          # repository: setaer
        

  cronjobexample-2:
    schedule: 0 3 * * 0
    serviceAccount: cronjobexample-2
    image: asdasd
    volumes: 
      - name: db-backups
        mountPath: /db-backups
        type:
          emptyDir: {}
      - name: my-configmap-volume
        mountPath: /etc/scripts
        type:
          configMap:
            name: db-backups-scripts
        configMapData:
          test_script.sh: |
            #!/bin/bash
            DATE=$(date +%d_%m)
    #'{{ .Files.Get "scripts/test_script.sh" | nindent 4 }}' we are currently working on making configMap script data workable from a repo that's not standard library, for now you can use it like this.
        
    nodeSelector:
      node-label: "my-node-pool" # Optional, if not specified it defaults to the default node selector for the cluster
    tolerations:
      - key: purpose
        operator: Equal
        value: run-example-app-1a-node
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-preemptible
              operator: DoesNotExist
    initContainers:
      exampleinitcontainer-1:
        image: google/cloud-sdk
        command: ["/bin/sh", "-c"]
        args:
          - /etc/scripts/script1.sh
        secrets:
          dataFrom:
            - data-from-secret-1
            - data/from/secret/two

      exampleinitcontainer-2:
        image: asdasd
        args: 
          - gsutil 
          - cp 
          - -r
          - gs://cloudkite-bucket/path
          - /db-backups/

    containers:
      examplecontainer:
        image: us-central1-docker.pkg.dev/cloudkite-infra-ops/cloudkite-docker-images/cloudkite
        tag: stage
        command: ["/bin/sh", "-c"]
        args: ["node", "example_app.js"]
        secrets:
          - secretKey: appsettings.json
            property: APPSETTINGS_JSON
          - secretKey: SOURCE_PROJECT_ID
healthCheckPolicy:
  port: 80 # Optional, defaults to 80
  requestPath: / # Optional, defaults to /
  targetServiceName: api-documentation-tcp # Required, the name of the service to which the health check policy applies. Should correspond to HttpRoute service name.
