{{- range $name, $config := .Values.gateways }}
{{- if $config.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
    {{- with $config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ required "gatewayClass is required" $config.gatewayClass }}
  listeners:
    {{- toYaml $config.listeners | nindent 4 }}
  {{- if $config.addresses }}
  addresses:
    {{- toYaml $config.addresses | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
