{{- if .Values.ingress  }} # NOTE: >0.8.0 DEPRECATES this, USE .Values.ingresses
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ $.Release.Name }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  {{- if .Values.ingress.hostPaths }}
  {{- range .Values.ingress.hostPaths }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
  {{- end }}
  {{- else if .Values.ingress.hosts }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $.Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
  {{- end }}
  {{- end }}
  tls:
  {{- if .Values.ingress.tls }}
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{ else }}
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ . | quote }}
      secretName: {{ $.Values.ingress.secretName | default . | replace "." "-" | replace "*" "star" }}-tls
    {{- end }}
  {{- end }}
---
{{- end }}
---
{{- range $ingName, $ingConfig := .Values.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $ingConfig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with $ingConfig.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- with $ingConfig.ingressClass }}
  ingressClassName: {{ $ingConfig.ingressClass }}
  {{- end }}
  tls:
  {{- if $ingConfig.tls }}
    {{- toYaml $ingConfig.tls | nindent 4 }}
  {{ else }}
    {{- range $ingConfig.hosts }}
    - hosts:
        - {{ . | quote }}
      secretName: {{ . | replace "." "-" | replace "*" "star" }}-tls
    {{- end }}
  {{- end }}
  rules:
  {{- range $ingConfig.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $ingConfig.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
  {{- end }}
---
{{- end }}