# deployment services
{{ range $appName, $appConfig := .Values.apps }}
{{- $appValues := dict
      "component" $appName
      "Values"    $.Values
      "Release"   $.Release
      "labels"    (default (dict) $.Values.labels)
    -}}

# deployment global services
{{- if $appConfig.services }}
{{- range $appConfig.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if .fullname }}{{ .fullname }}{{ else }}{{ $appName }}-{{ .name }}{{ end }}
  {{- include "standard-app.labels" $appValues | nindent 2 }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    app: {{ $appName }}
---
{{- end }}
{{- end }}

# rollout services
# rollout global service
{{- if $appConfig.rollout }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-canary
  {{- include "standard-app.labels" $appValues | nindent 2 }}
spec:
  type: {{ $appConfig.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $appConfig.service.port }}
      name: {{ $appConfig.service.name }}
      targetPort: {{ $appConfig.service.targetPort }}
      protocol: {{ $appConfig.service.protocol }}
  selector:
    app: {{ $appName }}
---
{{- end }}
{{- end }}
