{{ range $appName, $appConfig := .Values.apps }}
{{ with $appConfig.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $appName }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: {{ .path | default "/metrics"}}
    interval: {{ .interval | default "30s"}}
    port: {{ .port }}
    scrapeTimeout: {{ .scrapeTimeout | default "30s"}}
  namespaceSelector:
    matchNames:
      - {{ .namespace | default $.Release.Namespace }}
  selector:
    matchLabels:
      app: {{ $appName }}
{{- end }}
{{- end }}
