# deployment services
{{ range $appName, $appConfig := .Values.apps }}

# deployment global services
{{- if $appConfig.services }}
{{- range $appConfig.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else if .fullname }}{{ .fullname }}{{ else }}{{ $appName }}-{{ .name }}{{ end }}
  labels:
    app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    - port: {{ .externalPort }}
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  selector:
    app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Release.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
---
{{- end }}
{{- end }}

# rollout services
# rollout global service
{{- if $appConfig.rollout }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Chart.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}-canary
  labels:
    app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Chart.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $appConfig.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $appConfig.service.port }}
      name: {{ $appConfig.service.name }}
      targetPort: {{ $appConfig.service.targetPort }}
      protocol: {{ $appConfig.service.protocol }}
  selector:
    app: {{ if $.Values.pr }}{{ $.Release.Name }}-{{ $appName | trimPrefix $.Chart.Name | trimPrefix "-" }}{{ else }}{{ $appName }}{{ end }}
---
{{- end }}
{{- end }}