# app services
{{ range $appName, $appConfig := .Values.apps }}
{{- $appValues := dict
      "component" $appName
      "Values"    $.Values
      "Release"   $.Release
      "labels"    (default (dict) $.Values.labels)
    -}}

# app global services
{{- if $appConfig.services }}
{{- range $appConfig.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if .fullname }}{{ .fullname }}{{ else }}{{ $appName }}-{{ .name }}{{ end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "standard-app.labels" $appValues | nindent 2 }}
  {{- with $appConfig.serviceAnnotations }}
  annotations:
  {{ toYaml . | indent 2 }}
  {{- end }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    app: {{ $appName }}
---
{{- end }}
{{- end }}
{{- end }}
