# deployment services
{{ range $appName, $appConfig := .Values.apps }}

# deployment global services
{{- if $appConfig.services }}
{{- range $appConfig.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if .fullname }}{{ .fullname }}{{ else }}{{ $appName }}-{{ .name }}{{ end }}
  labels:
    app: {{ $appName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    app: {{ $appName }}
---
{{- end }}
{{- end }}

# rollout services
# rollout global service
{{- if $appConfig.rollout }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-canary
  labels:
    app: {{ $appName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $appConfig.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $appConfig.service.port }}
      name: {{ $appConfig.service.name }}
      targetPort: {{ $appConfig.service.targetPort }}
      protocol: {{ $appConfig.service.protocol }}
  selector:
    app: {{ $appName }}
---
{{- end }}
{{- end }}