{{ range $appName, $appConfig := .Values.apps }}
{{- if $appConfig.hpa }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  maxReplicas: {{ $appConfig.hpa.maxReplicas }}
  minReplicas: {{ $appConfig.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: {{ if $appConfig.rollout }}argoproj.io/v1alpha1{{ else }}apps/v1{{ end }}
    kind: {{ if $appConfig.rollout }}Rollout{{ else }}Deployment{{ end }}
    name: {{ $appName }}
  metrics:
  {{- with $appConfig.hpa.memoryTarget }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with $appConfig.hpa.cpuTarget }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
---
{{- end }}
{{- end }}