{{ range $appName, $appConfig := .Values.apps }}
{{- if $appConfig.mpa }}
apiVersion: autoscaling.gke.io/v1beta1
kind: MultidimPodAutoscaler
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ if $appConfig.rollout }}argoproj.io/v1alpha1{{ else }}apps/v1{{ end }}
    kind: {{ if $appConfig.rollout }}Rollout{{ else }}Deployment{{ end }}
    name: {{ $appName }}
  goals:
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $appConfig.mpa.cpuTarget }}
  constraints:
    global:
      minReplicas: {{ $appConfig.mpa.minReplicas }}
      maxReplicas: {{ $appConfig.mpa.maxReplicas }}
    containerControlledResources: [ memory ]
    container:
    - name: '*'
      {{- with $appConfig.mpa.resources }}
      requests:
        {{- toYaml . | nindent 8}}
      {{- end }}
  policy:
    updateMode: {{ if eq $appConfig.mpa.mode "noset" }}"Off"{{ else }}"Auto"{{ end }}
---
{{- end }}
{{- end }}