{{- range $cronjobName, $cronjobConfig := .Values.cronjobs }}
{{- $cronjobValues := dict
      "component" $cronjobName
      "Values"    $.Values
      "Release"   $.Release
      "labels"    (default (dict) $.Values.labels)
    -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjobName }}
  {{- include "standard-app.labels" $cronjobValues | nindent 2 }}
spec:
  schedule: {{ $cronjobConfig.schedule | quote }}
  suspend: {{ $cronjobConfig.suspend | default "false" }}
  concurrencyPolicy: {{ $cronjobConfig.concurrencyPolicy | default "Replace" }}
  jobTemplate:
    metadata:
      name: {{ $cronjobName }}
      {{- include "standard-app.labels" $cronjobValues | nindent 6 }}
    spec:
      backoffLimit: {{ $cronjobConfig.backoffLImit | default "0" }}
      template:
        metadata:
          {{- include "standard-app.labels" $cronjobValues | nindent 10 }}
        spec:
          {{- if $cronjobConfig.affinity }}
          affinity:
            {{- toYaml $cronjobConfig.affinity | nindent 12 }}
          {{- end }}
          {{- if $cronjobConfig.tolerations }}
          tolerations:
            {{- toYaml $cronjobConfig.tolerations | nindent 12 }}
          {{- end }}
          {{- if $cronjobConfig.nodeSelector }}
          nodeSelector:
            {{- toYaml $cronjobConfig.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if $cronjobConfig.serviceAccount }}
          serviceAccountName: {{ $cronjobConfig.serviceAccount }}
          {{- end }}
          {{- if $cronjobConfig.initContainers }}
          initContainers:
            {{- range $initContainerName, $initContainerConfig  := $cronjobConfig.initContainers }}
              {{- include "standard-app.container" (dict "name" $initContainerName "container" $initContainerConfig "app" $cronjobConfig "cronjobName" $cronjobName "Values" $.Values) | nindent 12 }}
            {{- end }}
          {{- end }}
          containers:
          {{- range $containerName, $containerConfig := $cronjobConfig.containers }}
            {{- include "standard-app.container" (dict "name" $containerName "container" $containerConfig "app" $cronjobConfig "cronjobName" $cronjobName "Values" $.Values) | nindent 12 }}
          {{- end }}
          {{- if $cronjobConfig.volumes }}
          volumes:
            {{- range $cronjobConfig.volumes }}
            - name: {{ .name }}
              {{- with .type }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
          {{- end }}
          restartPolicy: {{ $cronjobConfig.restartPolicy | default "Never"}}
---
{{- end }}