{{- range $cronjobName, $cronjobConfig := .Values.cronjobs }}
{{- $cronjobValues := dict
      "component" $cronjobName
      "Values"    $.Values
      "Release"   $.Release
      "labels"    (default (dict) $.Values.labels)
    }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjobName }}
  {{- include "standard-app.labels" $cronjobValues | nindent 2 }}
spec:
  schedule: {{ $cronjobConfig.schedule | quote }}
  suspend: {{ $cronjobConfig.suspend | default "false" }}
  concurrencyPolicy: {{ $cronjobConfig.concurrencyPolicy | default "Replace" }}
  jobTemplate:
    metadata:
      name: {{ $cronjobName }}
      {{- include "standard-app.labels" $cronjobValues | nindent 6 }}
    spec:
      backoffLimit: {{ $cronjobConfig.backoffLimit | default "0" }}
      template:
        metadata:
          {{- include "standard-app.labels" $cronjobValues | nindent 10 }}
        spec:
          {{- if or $cronjobConfig.affinity $.Values.preferSpot }}
          affinity:
            {{- $jobAffinity := default dict $cronjobConfig.affinity }}
            {{- $spotAffinity := fromYaml (include "standard-app.spotNodeSelection.nodeAffinity" $ | trim) }}
            {{- toYaml (merge $spotAffinity $jobAffinity) | nindent 10 }}
          {{- end }}
          {{- if or $cronjobConfig.tolerations $.Values.preferSpot }}
          tolerations:
            {{- if $cronjobConfig.tolerations }}
              {{- toYaml $cronjobConfig.tolerations | nindent 12 }}
            {{- end }}
            {{- if $.Values.preferSpot }}
              {{- include "standard-app.spotNodeSelection.toleration" $ | trim | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if $cronjobConfig.nodeSelector }}
          nodeSelector:
            {{- toYaml $cronjobConfig.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if $cronjobConfig.serviceAccount }}
          serviceAccountName: {{ $cronjobConfig.serviceAccount }}
          {{- end }}
          {{- if $cronjobConfig.initContainers }}
          initContainers:
            {{- range $initContainerName, $initContainerConfig  := $cronjobConfig.initContainers }}
              {{- include "standard-app.container" (dict "isInitContainer" true "name" $initContainerName "container" $initContainerConfig "app" $cronjobConfig "appName" $cronjobName "global" $.Values "releaseName" $.Release.Name) | nindent 12 }}
            {{- end }}
          {{- end }}
          containers:
          {{- if $cronjobConfig.containers }}
            {{- range $containerName, $containerConfig := $cronjobConfig.containers }}
              {{- include "standard-app.container" (dict "name" $containerName "container" $containerConfig "app" $cronjobConfig "appName" $cronjobName "global" $.Values "releaseName" $.Release.Name) | nindent 12 }}
            {{- end }}
          {{- else }}
            {{- include "standard-app.container" (dict "name" $cronjobName "container" (dict) "app" $cronjobConfig "appName" $cronjobName "global" $.Values "releaseName" $.Release.Name) | nindent 12 }}
          {{- end }}
          {{- if $cronjobConfig.volumes }}
          volumes:
            {{- range $cronjobConfig.volumes }}
            - name: {{ .name }}
              {{- with .type }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
          {{- end }}
          restartPolicy: {{ $cronjobConfig.restartPolicy | default "Never"}}
---
{{- end }}
