{{- range $appName, $appConfig := .Values.apps }}
{{- $appValues := dict
      "component" $appName
      "Values"    $.Values
      "Release"   $.Release
      "labels"    (default (dict) $.Values.labels)
    -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "standard-app.labels" $appValues | nindent 2 }}
    {{- with $appConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not $appConfig.hpa }}
  replicas: {{ $appConfig.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ $appConfig.revisionHistoryLimit | default 2 }}
  {{- if $appConfig.strategyType }}
  strategy:
    type: {{ $appConfig.strategyType }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        {{- include "standard-app.labels" $appValues | nindent 6 }}
        {{- with $appConfig.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if $appConfig.podAnnotations }}
        {{- toYaml $appConfig.podAnnotations | nindent 8 }}
        {{- end }}
        reloader.stakater.com/auto: "true"
    spec:
      {{- if or $appConfig.affinity $.Values.preferSpot }}
      affinity:
        {{- $jobAffinity := default dict $appConfig.affinity }}
        {{- $spotAffinity := fromYaml (include "standard-app.spotNodeSelection.nodeAffinity" $ | trim) }}
        {{- toYaml (merge $spotAffinity $jobAffinity) | nindent 8 }}
      {{- end }}
      {{- if or $appConfig.tolerations $.Values.preferSpot }}
      tolerations:
        {{- if $appConfig.tolerations }}
          {{- toYaml $appConfig.tolerations | nindent 8 }}
        {{- end }}
        {{- if  $.Values.preferSpot }}
          {{- include "standard-app.spotNodeSelection.toleration" $ | trim | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if $appConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml $appConfig.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $appConfig.podSecurityContext }}
      securityContext:
        {{- toYaml $appConfig.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if $appConfig.serviceAccount }}
      serviceAccountName: {{ $appConfig.serviceAccount }}
      {{- end }}
      {{- if $appConfig.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $appConfig.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if $appConfig.initContainers }}
      initContainers:
        {{- range $initContainerName, $initContainerConfig  := $appConfig.initContainers }}
          {{- include "standard-app.container" (dict "isInitContainer" true "name" $initContainerName "container" $initContainerConfig "app" $appConfig "appName" $appName "global" $.Values "releaseName" $.Release.Name) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
      {{- if $appConfig.containers }}
        {{- range $containerName, $containerConfig  := $appConfig.containers }}
          {{- include "standard-app.container" (dict "name" $containerName "container" $containerConfig "app" $appConfig "appName" $appName "global" $.Values "releaseName" $.Release.Name) | nindent 8 }}
        {{- end }}
      {{- else }}
        {{- include "standard-app.container" (dict "name" $appName "container" (dict) "app" $appConfig "appName" $appName "global" $.Values "releaseName" $.Release.Name) | nindent 8 }}
      {{- end }}  
      {{- if $appConfig.volumes }}
      volumes:
        {{- range $appConfig.volumes }}
        - name: {{ .name }}
          {{- with .type }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- end }}  
---
{{- end }}
