{{- range $jobName, $jobConfig := .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: "{{ $jobName }}-"
  {{- with $jobConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ $jobName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }} 
spec:
  template:
    metadata:
      labels:
        app: {{ $jobName }}
        product: {{ $.Release.Name }}
        {{- with $.Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if eq $.Values.nodeType "spot" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                - "true"
      tolerations:
        - effect: NoSchedule
          key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
      {{- end }}
      {{- if $jobConfig.serviceAccount }}
      serviceAccountName: {{ $jobConfig.serviceAccount }}
      {{- end }}
      containers:
        - name: {{ $.Release.Name }}-{{ $jobName }}
          image: "{{- $jobConfig.image | default $.Values.image.repository }}:{{- $jobConfig.tag | default $.Values.image.tag }}"
          imagePullPolicy: "{{- $jobConfig.imagePullPolicy | default $.Values.imagePullPolicy }}"
          {{- if $jobConfig.command }}
          command: 
            {{- range $jobConfig.command }}
            - {{ . | quote}}
            {{- end }}
          {{- end }}
          {{- if $jobConfig.args | quote }}
          args:
            {{- range $jobConfig.args }}
            - {{ . }}
            {{- end }}
          {{- end }}
          env:
            {{- range $key, $value := merge (default dict $jobConfig.env) (default dict $.Values.env) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            {{- if $jobConfig.secrets }}
            - secretRef:
                name: {{ $jobName }}
            {{- end }}
            {{- if $.Values.secrets }}
            - secretRef:
                name: {{ $.Release.Name }}
            {{- end }}
          {{- with $jobConfig.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $jobConfig.volumes }}
          volumeMounts:
            {{- range $jobConfig.volumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- if $jobConfig.volumes }}
      volumes:
        {{- range $jobConfig.volumes }}
        - name: {{ .name }}
          {{- with .type }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- end }}      
      restartPolicy: {{ $jobConfig.restartPolicy | default "Never" }}      
---
{{- end }}