{{- range $jobName, $jobConfig := .Values.jobs }}
{{- $jobValues := dict
      "component" $jobName
      "Values"    $.Values
      "Release"   $.Release
      "labels"    (default (dict) $.Values.labels)
    -}}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if eq $jobConfig.useNamePrefix false }}
  name: {{ $jobName }}
  {{- else }}
  generateName: "{{ $jobName }}-"
  {{- end }}
  {{- with $jobConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "standard-app.labels" $jobValues | nindent 2 }}
    {{- with $jobConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $jobConfig.specOptions }}
  {{- toYaml $jobConfig.specOptions | nindent 2 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "standard-app.labels" $jobValues | nindent 6 }}
        {{- with $jobConfig.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or $jobConfig.affinity $.Values.preferSpot }}
      affinity:
        {{- $jobAffinity := default dict $jobConfig.affinity }}
        {{- $spotAffinity := fromYaml (include "standard-app.spotNodeSelection.nodeAffinity" $ | trim) }}
        {{- toYaml (merge $spotAffinity $jobAffinity) | nindent 8 }}
      {{- end }}
      {{- if or $jobConfig.tolerations $.Values.preferSpot }}
      tolerations:
        {{- if $jobConfig.tolerations }}
          {{- toYaml $jobConfig.tolerations | nindent 8 }}
        {{- end }}
        {{- if $.Values.preferSpot }}
          {{- include "standard-app.spotNodeSelection.toleration" $ | trim | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if $jobConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml $jobConfig.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $jobConfig.serviceAccount }}
      serviceAccountName: {{ $jobConfig.serviceAccount }}
      {{- end }}
      containers:
          {{- if $jobConfig.containers }}
        {{- range $containerName, $containerConfig  := $jobConfig.containers }}
          {{- include "standard-app.container" (dict "name" $containerName "container" $containerConfig "app" $jobConfig "appName" $jobName "global" $.Values "releaseName" $.Release.Name) | nindent 8 }}
        {{- end }}
      {{- else }}
        {{- include "standard-app.container" (dict "name" $jobName "container" (dict) "app" $jobConfig "appName" $jobName "global" $.Values "releaseName" $.Release.Name) | nindent 8 }}
      {{- end }}
      {{- if $jobConfig.volumes }}
      volumes:
        {{- range $jobConfig.volumes }}
        - name: {{ .name }}
          {{- with .type }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- end }}      
      restartPolicy: {{ $jobConfig.restartPolicy | default "Never" }}      
---
{{- end }}
