{{- range $jobName, $jobConfig := .Values.jobs }}
{{- $jobValues := dict
      "component" $jobName
      "Values"    $.Values
      "Release"   $.Release
      "labels"    (default (dict) $.Values.labels)
    -}}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: "{{ $jobName }}-"
  {{- with $jobConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- include "standard-app.labels" $jobValues | nindent 2 }}
spec:
  template:
    metadata:
      {{- include "standard-app.labels" $jobValues | nindent 6 }}
    spec:
      {{- if $jobConfig.affinity }}
      affinity:
        {{- toYaml $jobConfig.affinity | nindent 8 }}
      {{- end }}
      {{- if $jobConfig.tolerations }}
      tolerations:
        {{- toYaml $jobConfig.tolerations | nindent 8 }}
      {{- end }}
      {{- if $jobConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml $jobConfig.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $jobConfig.serviceAccount }}
      serviceAccountName: {{ $jobConfig.serviceAccount }}
      {{- end }}
      containers:
          {{- if $jobConfig.containers }}
        {{- range $containerName, $containerConfig  := $jobConfig.containers }}
          {{- include "standard-app.container" (dict "name" $containerName "container" $containerConfig "app" $jobConfig "appName" $jobName "global" $.Values) | nindent 8 }}
        {{- end }}
      {{- else }}
        {{- include "standard-app.container" (dict "name" $jobName "container" (dict) "app" $jobConfig "appName" $jobName "global" $.Values) | nindent 8 }}
      {{- end }}
      {{- if $jobConfig.volumes }}
      volumes:
        {{- range $jobConfig.volumes }}
        - name: {{ .name }}
          {{- with .type }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- end }}      
      restartPolicy: {{ $jobConfig.restartPolicy | default "Never" }}      
---
{{- end }}
